server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: wiki-web
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        url-pattern:
          #开启监控页面
          enabled: true
          #访问监控地址
          url-pattern: /druid/*
          #用户名、密码
          login-username: admin
          login-password: admin
    #多数据源配置
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      strict: false
      datasource:
        #master数据源
        master:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/wiki?useSSL=false&useUnicode=true&autoReconnect=true&allowMultiQueries=true&failOverReadOnly=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: root
          password: admin
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化时建立物理连接的个数，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 200
        # 配置获取连接时最大等待时间，单位毫秒
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 用来检测连接是否有效的sql，要求是一个查询语句
        validation-query: select 1
        # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        testWhileIdle: true
        # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnBorrow: false
        # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnReturn: false
        # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
        poolPreparedStatements: true
        # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties:
          druid.stat.mergeSql: true
          druid.stat.slowSqlMillis: 5000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #redis集群
  redis:
    password: Admin123
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379
    timeout: 10000
    keyPrefix: 'wiki:'
    jedis:
      pool:
        max-active: 150
        max-idle: 10
        min-idle: 1
        max-wait: 3000
        time-between-eviction-runs: 50
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      location: /var/tmp
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 200MB
  task:
    execution:
      pool:
        # 线程数 默认8
        core-pool-size: 8
        max-pool-size: 50
        queue-capacity: 100
        keep-alive-seconds: 60


mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔
  mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    banner: true
    db-config:
      # 主键类型 0-"AUTO 数据库ID自增"，1-"NONE该类型为未设置主键类型"，2:"INPUT用户输入ID"，3:"ASSIGN_ID 全局唯一ID (数字类型唯一ID) mybatis-plus默认主键类型"，4:"ASSIGN_UUID全局唯一ID UUID";
      id-type: ASSIGN_ID
      update-strategy: NOT_EMPTY
      insert-strategy: NOT_EMPTY
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true

